In [1]:
np.random()

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [5]:
np.random()

TypeError: 'module' object is not callable

In [7]:
np.random

<module 'numpy.random' from 'C:\\Users\\aarya\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [21]:
np.random.random(10)

array([0.0070453 , 0.93125014, 0.14362672, 0.19453582, 0.88789647,
       0.01334101, 0.5492829 , 0.42079458, 0.93897452, 0.41133226])

In [23]:
big_array = np.random.rand(1000000)

In [25]:
big_array

array([0.072217  , 0.64163982, 0.69861834, ..., 0.65740749, 0.30396159,
       0.90557762])

In [29]:
np.max(big_array)

0.9999973477191351

In [33]:
np.min(big_array)

1.913368244954583e-07

In [35]:
print(big_array.min(), big_array.max(), big_array.sum())

1.913368244954583e-07 0.9999973477191351 499954.88906455645


In [37]:
M = np.random.random((3, 4))
print(M)

[[0.60624172 0.89256151 0.35857825 0.13767414]
 [0.31867041 0.0936044  0.73835371 0.47607761]
 [0.65646397 0.77063042 0.48494505 0.47240267]]


In [47]:
np.sum(M)

6.006203858341074

In [43]:
np.max(M,axis=0)

array([0.65646397, 0.89256151, 0.73835371, 0.47607761])

In [49]:
np.max(M,axis=1)

array([0.89256151, 0.73835371, 0.77063042])