In [21]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) 

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [33]:
x3.ndim #this prints the number of dimensions of x3

3

In [31]:
x1.ndim

1

In [35]:
x3.shape

(3, 4, 5)

In [37]:
type(x3.shape)

tuple

In [43]:
x1.dtype

dtype('int32')

In [45]:
x3[0,3,2]

3

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [50]:
x3[0,1,1]=3.14

In [54]:
x3[0]

array([[8, 1, 5, 9, 8],
       [9, 3, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7]])

x[start:stop:step] is used for slicing

In [59]:
x1[1:4]

array([0, 3, 3])

In [65]:
x2[1:4:2]

array([[7, 6, 8, 8]])

In [67]:
x4=np.arange(12)

In [69]:
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [73]:
x2[1,3]

8

In [77]:
x2[:3,:2]

array([[3, 5],
       [7, 6],
       [1, 6]])

In [79]:
x2[:,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [83]:
x2[0]

array([3, 5, 2, 4])

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [86]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [88]:
x10=x2[:2,:2]

In [90]:
x10

array([[3, 5],
       [7, 6]])

In [92]:
x10[0,1]=10

In [94]:
x10

array([[ 3, 10],
       [ 7,  6]])

In [96]:
x2

array([[ 3, 10,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

0,1 value was changed in the original array as well, so it returns references

to create a copy, use the .copy() method

In [102]:
x10=x2[:2,:2].copy()

In [104]:
x10

array([[ 3, 10],
       [ 7,  6]])

In [106]:
x10[0,1]=5

In [108]:
x2

array([[ 3, 10,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [110]:
x10

array([[3, 5],
       [7, 6]])

# Rearranging in numpy

### rearanging can be done using the reshape(row,column) method

In [115]:
ran=np.arange(10).reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [117]:
ran=np.arange(10).reshape(3,2)

ValueError: cannot reshape array of size 10 into shape (3,2)

In [119]:
ran=np.arange(10).reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [121]:
ran=np.arange(10).reshape(5,2)

In [123]:
ran

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [125]:
ran.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
ran

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [129]:
ran=ran.flatten()

In [131]:
ran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
ran.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [135]:
ran=ran.reshape((5,2))

# Concatenation

In [144]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [146]:
z=np.array((1,2,3))

In [148]:
y

array([3, 2, 1])

In [150]:
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [154]:
sorted(np.concatenate([x,y,z]))

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [156]:
grid=np.array([[1,2,3],[4,5,6]])

In [158]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [162]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [171]:
np.vstack([[1,2,3],grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [173]:
np.hstack([[[1,2],[3,4]],grid])

array([[1, 2, 1, 2, 3],
       [3, 4, 4, 5, 6]])

## Splitting array

In [178]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #splits the array into 3 parts by creating a middle array from index 3 to 5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [180]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])