In [3]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6])

In [5]:
x>3

array([False, False, False,  True,  True,  True])

In [11]:
(2*x)==(2**x)

array([ True,  True, False, False, False, False])

As in the case of arithmetic operators, the comparison operators are implemented as ufuncs in NumPy; for example, when you write x < 3, internally NumPy uses np.less(x, 3)

## Counting entries

To count the number of True entries in a Boolean array, np.count_nonzero is useful:

In [17]:
np.count_nonzero(x>3)

3

one can also use the sum function as false is interpreted as zero

In [20]:
np.sum(x>3)

3

In [22]:
x=np.random.randint(10,size=(3,3))

In [24]:
x

array([[0, 1, 8],
       [4, 8, 4],
       [2, 4, 3]])

In [28]:
np.sum(x>=4,axis=1)

array([1, 3, 1])

np.any() can be used to check if there exists any value where.... and np.all() is used to check if all the values satisfy the condition

In [32]:
np.any(x>=10)

False

In [34]:
np.all(x>=0)

True

In [38]:
np.sum((x<10) & (x>5))

2

In [5]:
x=np.random.randint(10,size=(3,3))

In [9]:
x

array([[6, 9, 2],
       [7, 1, 3],
       [3, 2, 4]])

to get the array and not true and false on a condition:

In [11]:
x[x>5]

array([6, 9, 7])

In [15]:
np.greater_equal(x,5,out=x)

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [17]:
x

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])