In [3]:
import numpy as np

In [5]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [7]:
a + 5

array([5, 6, 7])

In [9]:
a

array([0, 1, 2])

In [11]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [15]:
a = np.arange(3)
b = np.arange(3)

In [17]:
print(a)
print(b)

[0 1 2]
[0 1 2]


In [19]:
a + b

array([0, 2, 4])

## Rules of Broadcasting

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [29]:
# Rule 1

M = np.ones((2, 3))
a = np.arange(3)
print(a,M)

[0 1 2] [[1. 1. 1.]
 [1. 1. 1.]]
