# pandas is fast in computation

In [4]:
import numpy as np

In [58]:
np.random.seed(0)
x1=np.random.randint(10,size=6)

In [60]:
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
1/x1

C:\Users\aarya\AppData\Local\Temp\ipykernel_42148\4108178241.py:1: RuntimeWarning: divide by zero encountered in divide
  1/x1


array([0.2       ,        inf, 0.33333333, 0.33333333, 0.14285714,
       0.11111111])

In [64]:
x2=np.arange(5)

In [66]:
x2

array([0, 1, 2, 3, 4])

In [68]:
x2/5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [70]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [72]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


### Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the + operator is a wrapper for the add function:

In [75]:
x.add(5)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [77]:
np.add(x,5)

array([5, 6, 7, 8])

## Absolute value

In [80]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [88]:
 theta = np.linspace(0, np.pi, 3)  #linspace creates evenly spaced values starting from the first argument and ending at 
#last argument, and the number of values

In [84]:
theta

array([0.        , 1.57079633, 3.14159265])

In [90]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [92]:
## inverse trigo fnctions
x=[-1,0,1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

### Logarithms and exponents

In [95]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [97]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


# Some advanced ufunc

## Storing output somewhere else

In [101]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [103]:
y

array([ 0., 10., 20., 30., 40.])

In [105]:
y=x*5

In [107]:
y=y*5

In [109]:
y

array([  0,  25,  50,  75, 100])

In [111]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


#### If we had instead written y[::2] = 2 ** x, this would have resulted in the creation of a temporary array to hold the results of 2 ** x, followed by a second operation copying those values into the y array. This doesn't make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the out argument can be significant.

## Aggregates

### Reduce

A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [117]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [119]:
np.multiply.reduce(x)

120

If we'd like to store all the intermediate results of the computation, we can instead use accumulate:

In [122]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

## Outer products

In [125]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])