## Fancy Indexing

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once. For example, consider the following array:

In [5]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [7]:
ind=[1,2,3]

In [9]:
x[ind]

array([92, 14, 71])

In [11]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [13]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3]) #0,2 1,1 and 2,3 will be printed
X[row, col]

array([ 2,  5, 11])

In [25]:
X[2,[1,2,3]].reshape(3,1)

array([[ 9],
       [10],
       [11]])

x=np.random.randint(10,size=6)

In [29]:
x

array([0, 5, 5, 8, 5, 8])

In [31]:
x[[1,2,3]]=10

In [51]:
x

array([ 0, 13, 11, 13,  5,  8])

In [41]:
ind=[1,1,3]

In [53]:
x[ind]+=1

In [55]:
x

array([ 0, 14, 11, 14,  5,  8])

notice how index 1 is incremented only one times when the index is included twice, thats because x+=1 transforms to x=x+1, so the augmentation does not happen multiple times but the assignment happens multiple times 

to perform augmentation, one can use the np.add.at() function

In [61]:
x = np.zeros(10)
np.add.at(x, ind, 1)
print(x)

[0. 2. 0. 1. 0. 0. 0. 0. 0. 0.]
