In [1]:
import numpy as np

In [5]:
x=np.random.randint(15,size=10)

In [7]:
np.sort(x)

array([ 1,  3,  3,  4,  5,  8,  9, 14, 14, 14])

In [9]:
x

array([ 4, 14, 14, 14,  1,  3,  9,  5,  8,  3])

arg sort returns the indexes of the sorted array

In [42]:
y=x[np.argsort(x)].copy()

In [44]:
y

array([ 1,  3,  3,  4,  5,  8,  9, 14, 14, 14])

## Sorting along rows or columns

In [59]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [61]:
np.sort(X, axis=0) #column sorting

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [67]:
np.sort(X,axis=1) #row sorting

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Partial sorts

NumPy provides this in the np.partition function. np.partition takes an array and a number K; the result is a new array with the smallest K values to the left of the partition, and the remaining values to the right, in arbitrary order:

In [71]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

Note that the first three values in the resulting array are the three smallest in the array, and the remaining array positions contain the remaining values. Within the two partitions, the elements have arbitrary order.

In [74]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

there is a np.argpartition that computes indices of the partition. 